version: '3.9'

services:
  api:
    container_name: api
    build: .
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    env_file:
      - .env
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:15-alpine
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env