create table if not exists categories
(
    id          bigint generated by default as identity primary key,
    name        varchar                           not null unique,
    description varchar                           null,
    parent      bigint references categories (id) null
);


create table if not exists teas
(
    id          bigint generated by default as identity primary key,
    name        varchar                           not null unique,
    description varchar                           null,
    price       bigint                            not null,
    updated_at  timestamp default now()           not null,
    id_category bigint references categories (id) not null
);



create table if not exists properties
(
    id    bigint generated by default as identity primary key,
    name  varchar    not null unique,
    color varchar(7) not null
);

create table if not exists teas_properties_link
(
    id          bigint generated by default as identity primary key,
    id_tea      bigint references teas (id),
    id_property bigint references properties (id)
);

create table if not exists users
(
    id         bigint primary key,
    username   varchar                 not null unique,
    name       varchar                 null,
    phone      varchar                 null unique,
    locale     varchar                 null,
    updated_at timestamp default now() not null
);

create table if not exists evaluations
(
    id      bigint generated by default as identity primary key,
    rating  decimal(4, 2) not null check ( rating > 0 and rating <= 10 ),
    note    varchar       null,
    id_user bigint references users (id),
    id_tea  bigint references teas (id)
)
